/**
 * The beOm mark: an ensō — the brush-drawn circle — with a dot at its centre.
 *
 * 원(O)은 완전함과 순환, 점(·)은 시작과 의식. The circle is left open, as an ensō
 * always is: the gap is the part that is still becoming.
 *
 * Drawn as a filled ribbon rather than a stroked circle. A constant-width stroke
 * reads as a geometric letter O; the width here swells through the belly and lifts
 * to a fine tail, which is what makes it a brushstroke. Generated by
 * scripts/gen-enso.mjs — edit the parameters there, not the coordinates.
 */
const ENSO_PATH =
  'M38.74,15.34L40.87,13.84L43.24,12.90L45.69,12.20L48.22,11.72L50.79,11.44L53.38,11.36L55.99,11.49L58.58,11.81L61.16,12.32L63.70,13.03L66.19,13.92L68.61,14.99L70.96,16.24L73.21,17.66L75.36,19.24L77.39,20.97L79.29,22.84L81.06,24.84L82.69,26.97L84.17,29.20L85.49,31.53L86.64,33.94L87.63,36.43L88.44,38.98L89.08,41.57L89.55,44.21L89.84,46.86L89.95,49.54L89.88,52.21L89.63,54.87L89.21,57.50L88.62,60.11L87.86,62.67L86.93,65.17L85.84,67.61L84.59,69.97L83.19,72.25L81.64,74.43L79.96,76.50L78.13,78.46L76.19,80.30L74.12,82.01L71.94,83.57L69.66,84.99L67.29,86.25L64.84,87.35L62.31,88.28L59.73,89.03L57.10,89.61L54.44,90.01L51.76,90.22L49.06,90.24L46.38,90.08L43.71,89.73L41.07,89.19L38.48,88.47L35.96,87.56L33.50,86.48L31.14,85.23L28.87,83.82L26.71,82.25L24.68,80.53L22.78,78.68L21.03,76.70L19.42,74.61L17.98,72.42L16.70,70.14L15.59,67.78L14.66,65.36L13.91,62.90L13.34,60.40L12.95,57.87L12.75,55.35L12.72,52.82L12.88,50.32L13.22,47.86L13.75,45.44L14.47,43.09L15.46,40.85L16.47,38.67L17.37,36.48L18.40,34.36L19.57,32.32L20.87,30.35L21.98,31.10L20.76,33.00L19.66,34.98L18.68,37.03L17.84,39.13L17.38,41.36L17.20,43.63L17.05,45.86L17.01,48.08L17.09,50.29L17.30,52.48L17.64,54.64L18.12,56.78L18.74,58.86L19.49,60.90L20.38,62.88L21.39,64.79L22.52,66.62L23.77,68.36L25.14,70.01L26.61,71.56L28.18,73.00L29.83,74.32L31.57,75.52L33.38,76.59L35.26,77.53L37.18,78.34L39.15,79.01L41.15,79.54L43.18,79.94L45.22,80.19L47.26,80.30L49.30,80.28L51.32,80.12L53.31,79.83L55.27,79.41L57.20,78.86L59.07,78.20L60.89,77.42L62.65,76.53L64.35,75.53L65.97,74.43L67.51,73.24L68.98,71.96L70.36,70.59L71.65,69.15L72.84,67.64L73.95,66.05L74.95,64.41L75.86,62.70L76.66,60.95L77.35,59.15L77.94,57.31L78.41,55.44L78.77,53.53L79.01,51.61L79.14,49.66L79.15,47.71L79.04,45.75L78.80,43.79L78.44,41.84L77.96,39.92L77.35,38.01L76.61,36.15L75.76,34.32L74.78,32.54L73.68,30.83L72.46,29.18L71.13,27.61L69.69,26.12L68.14,24.72L66.50,23.42L64.76,22.23L62.94,21.16L61.04,20.20L59.07,19.37L57.04,18.67L54.96,18.10L52.83,17.67L50.66,17.37L48.47,17.20L46.26,17.16L44.03,17.24L41.77,17.40L39.38,17.31Z';

export function Enso({
  className = '',
  dotClassName = 'fill-indigo-600 dark:fill-indigo-400',
}: {
  className?: string;
  dotClassName?: string;
}) {
  return (
    <svg viewBox="0 0 100 100" className={className} role="presentation" aria-hidden>
      <path d={ENSO_PATH} fill="currentColor" />
      <circle cx="50" cy="50" r="6" className={dotClassName} />
    </svg>
  );
}

/**
 * "be" + the ensō as the O + "m". The mark is the letter, so it scales with the type
 * rather than sitting beside it as a separate logo.
 */
export function Wordmark({ className = '', size = 'md' }: { className?: string; size?: 'sm' | 'md' | 'lg' }) {
  const type = size === 'lg' ? 'text-3xl' : size === 'sm' ? 'text-base' : 'text-xl';
  const ring = size === 'lg' ? 'h-9 w-9' : size === 'sm' ? 'h-5 w-5' : 'h-7 w-7';

  // The O is a graphic, so the text content alone reads "bem". Labelling the whole
  // lockup as one image gives assistive tech the actual name.
  return (
    <span
      role="img"
      aria-label="beOm"
      data-brand="beOm"
      className={`inline-flex items-center font-semibold tracking-tight text-slate-800 dark:text-slate-100 ${type} ${className}`}
    >
      <span aria-hidden>be</span>
      <Enso className={`${ring} -mx-[0.06em]`} />
      <span aria-hidden>m</span>
    </span>
  );
}

